ZachStallPortfolio/ZachStallPortfolio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from ZachStallPortfolio import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about_me/$', views.AboutMePage.as_view(), name='about_me'),
    url(r'^pc_builds/$', views.PcBuildsPage.as_view(), name='pc_builds'),
    url(r'^leela/$', views.LeelaPage.as_view(), name='leela'),
    url(r'', include('zBLOG.urls')),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout', kwargs = {'next_page':'zBLOG:post_list'}),
] # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ZachStallPortfolio/zBLOG/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from zBLOG import views

app_name = 'zBLOG'

urlpatterns = [
    url(r'^zblog/$', views.PostListView.as_view(), name='post_list'),
    url(r'^zblog_about/$', views.AboutView.as_view(), name='zblog_about'),
    url(r'^post/(?P<pk>\d+)$', views.PostDetailView.as_view(), name='post_detail'),
    url(r'^post/zblog_new/$', views.CreatePostView.as_view(), name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.PostUpdateView.as_view(), name='post_edit'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.PostDeleteView.as_view(), name='post_remove'),
    url(r'^drafts/$', views.DraftListView.as_view(), name='post_draft_list'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$',views.comment_approve,name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
]

ZachStallPortfolio/zBLOG/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse
from embed_video.fields import EmbedVideoField


# Create your models here.
class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length = 200)
    sub_title = models.CharField(max_length = 200)
    text = models.TextField()
    blog_image = models.ImageField( upload_to="upload_images",
                                    default = "upload_images/zBlog_index_image.jpg")
    post_video = EmbedVideoField(null=True, blank = True)
    create_date = models.DateTimeField(default = timezone.now)
    published_date = models.DateTimeField(blank = True, null = True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approve_comments(self):
        return self.comments.filter(approved_comment = True)

    def get_absolute_url(self):
        return reverse("zBLOG:post_detail", kwargs={'pk':self.pk})

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey('zBLOG.Post', related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse('zBLOG:post_list')

    def __str__(self):
        return self.text

ZachStallPortfolio/zBLOG/forms.py
from django import forms
from zBLOG.models import Post, Comment


class PostForm(forms.ModelForm):

    class Meta():
        model = Post
        fields = ('author', 'title', 'sub_title', 'text', 'blog_image', 'post_video')

        widgets = {
            'title':forms.TextInput(attrs={'class':'textinputclass'}),
            'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent'})
        }

class CommentForm(forms.ModelForm):

    class Meta():
        model = Comment
        fields = ('author', 'text')

        widgets = {
            'author':forms.TextInput(attrs={'class':'textinputclass'}),
            'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea'})

        }

ZachStallPortfolio/ZachStallPortfolio/views.py
from django.views.generic import TemplateView

class HomePage(TemplateView):
    template_name = 'ZSP/index.html'

class AboutMePage(TemplateView):
    template_name = 'ZSP/about_me.html'

class PcBuildsPage(TemplateView):
    template_name = 'ZSP/pc_builds.html'

class LeelaPage(TemplateView):
    template_name = 'ZSP/leela.html'

ZachStallPortfolio/zBLOG/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from zBLOG.models import Post, Comment
from zBLOG.forms import PostForm, CommentForm
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (  TemplateView, ListView,
                                    DetailView, CreateView,
                                    UpdateView, DeleteView,
                                    )
# Create your views here.

class AboutView(TemplateView):
    template_name = 'zBLOG/zblog_about.html'

class PostListView(ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

class PostDetailView(DetailView):
    model = Post

class CreatePostView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = 'zBLOG:post_detail.html'
    form_class = PostForm
    model = Post

class PostUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = 'zBLOG:post_detail.html'
    form_class = PostForm
    model = Post

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('zBLOG:post_list')

class DraftListView(LoginRequiredMixin, ListView):
     login_url = '/login/'
     redirect_field_name = 'zBLOG:post_list.html'
     model = Post

     def get_queryset(self):
         return Post.objects.filter(published_date__isnull=True).order_by('create_date')



################################################################################
################################################################################

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('zBLOG:post_detail', pk=pk)


# @login_required
def add_comment_to_post(request,pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('zBLOG:post_detail', pk=post.pk)

    else:
        form = CommentForm()
    return render(request, 'zBLOG/comment_form.html', {'form':form})


@login_required
def comment_approve(request,pk):
        comment = get_object_or_404(Comment,pk=pk)
        comment.approve()
        return redirect('zBLOG:post_detail',pk=comment.post.pk)

@login_required
def comment_remove(request, pk):
        comment = get_object_or_404(Comment, pk=pk)
        post_pk = comment.post.pk
        comment.delete()
        return redirect('zBLOG:post_detail', pk=post_pk)

ZachStallPortfolio/templates/ZSP/about_me.html
{% extends "base.html" %}
{% load staticfiles %}

 <!-- ----- INDEX NAV ----- -->
{% block nav %}
{% endblock %}
 <!-- ----- END INDEX NAV ----- -->

{% block content %}
  <!-- header content with image -->
  <div class="index_image container-fluid bg-2 text-center container-fluid-about" id="about_home">
    <h1>Zachary Stall</h1>
    <h4>Developer in Denver Colorado</h4>
    <!-- attention grabber image -->
    <img  class="img-responsive rounded-circle margin"
          src="{% static 'ZachStallPortfolio/about_media/aboutme_image.jpg' %}"
          alt="Pic Not Loadin - just my ugly mug"
          width="350"
          height="auto">
  </div>

  <!-- First Container -->
  <div class="container-fluid text-center container-fluid-about aboutme_font">
    <h3 class="margin">Jr Dev Ready to Make an Impact</h3>
    <div class="container">
      <p>I am a lifelong learner, who has found a intrinsic interest and passion
        for technology. I have an analytical mind, and love problem solving on
        all scales. At this point in my career, I am interested in and qualified
        for Junior or entry level development/engineering positions. My direct
        experience has been in HTML, CSS, JavaScript, PHP, and other tools to
        create online educational content (Lectora, Adobe, etc.). Through passion
        projects, formal educations, and self teaching I have experience with
        Python, Java, Django Framework, GitHub, Git, Anaconda (virtual environments)
        and have been exposed to SQL, PostgreSQL, and C#.
        My unique background as a high school mathematics teacher and school
        administrator has allowed me to develop a broad skill set. I am a
        strong problem solver, organizer, and collaborator.  I thrive in a team
        setting and I am eager to find a position where I can learn best practice
        and how to have a positive impact right away by working with a group of
        experienced developers. If you’d like to learn more about me or my background,
        please contact me directly at <a id="email" href="mailto: zach.stall.dev@gmail.com"> zach.stall.dev@gmail.com </a>
        or review my resume below.
      </p>
    </div>
  </div>

  <!-- Second Container -->
  <div class="container-fluid bg-2 text-center container-fluid-about">
    <h3 class="margin">Resume</h3>
    <embed  type="application/pdf"
            src="{% static 'ZachStallPortfolio/about_media/resume.pdf' %}"
            width="75%" height="600px">
  </div>

  <!-- Third Container -->
  <div class="container-fluid text-center container-fluid-about aboutme_font">
    <h3 class="margin">More About Me</h3>
    <div class="row">
      <div class="col-sm-4">
        <p>I am a Colorado native. I grew up in Lyons Colorado and attended Lyons
          Middle/Senior High. My senior year our high school football team made
          the 1A state championship game. I had a great high school experience,
          and this is what ultimately lead me to pursuing a career in education.
          I went to Colorado State University and earned a BS in Mathematics.
          At the end of college I met Caitlin, my beautiful wife. I started
          teaching math and coaching at Thompson Valley High School in Loveland
          Colorado.</p>
      </div>
      <div class="col-sm-4">
        <p> I completed my MS in Administration from CSU, and wound up
          finding a job in Denver at Manual High School where I taught math and
          joined their leadership team. After four rewarding years at Manual, I
          took a administrative position at Bennett School District where I
          eventually earned the Bennett Middle School Principal position.
          My whole life I have had a passion for technology. As a hobby I have
          built computers for myself and friends. </p>
      </div>
      <div class="col-sm-4">
        <p> As I got more and more into
            building computers I started exploring programming.
            One of the first books I remember reading was “How to Automate the Boring Stuff” by Al
            Sweigart. I was hooked, and extremely lucky to have a wife who supports
            me in pursuing my passion. In the spring of 2016 I started taking night
            courses and actively working towards changing careers. It has been
            very challenging, and even more rewarding. I am excited to see what
            the future brings! </p>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-4">
        <img  class="hover-shadow"
              src="{% static 'ZachStallPortfolio/about_media/aboutme_image_alt.jpg' %}"
              class="img-responsive margin"
              style="width:80%; padding-bottom:5px;"
              alt="img not working. :(">
      </div>
      <div class="col-sm-4">
        <img  class="hover-shadow"
              src="{% static 'ZachStallPortfolio/about_media/aboutme_zc_image.jpg' %}"
              class="img-responsive margin"
              style="width:80%; padding-bottom:5px;"
              alt="img not working. :(">
      </div>
      <div class="col-sm-4">
        <img  class="hover-shadow"
              src="{% static 'ZachStallPortfolio/about_media/aboutme_image.jpg' %}"
              class="img-responsive margin"
              style="width:80%; padding-bottom:5px;"
              alt="img not working. :(">
      </div>
    </div>
  </div>

{% endblock %}

ZachStallPortfolio/templates/zBLOG/comment_form.html
{% extends "base.html" %}
{% load staticfiles %}


 <!-- ----- INDEX NAV ----- -->
{% block nav %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'zBLOG:zblog_about' %}">zBlog About</a>
  </li>
</ul>
<ul class="navbar-nav ml-auto">
{% if user.is_authenticated %}
  <li class="nav-item ml-auto">
    <a class="nav-link" href="{% url 'zBLOG:post_new' %}">New Post</a>
  </li>
  <li class="nav-item ml-auto">
    <a class="nav-link navbar-right" href="{% url 'zBLOG:post_draft_list' %}">Drafts</a>
  </li>
  <li class="nav-item ml-auto">
    <a class="nav-link navbar-right" href="{% url 'logout' %}">Log Out</a>
  </li>
  <li class="nav-item ml-auto">
    <a class="nav-link navbar-right">Welcome: {{user.username}}</a>
  </li>
{% else %}
  <li class="nav-item ml-auto">
    <a class="nav-link ml-auto" href="{% url 'login' %}">Login</a>
  </li>
{% endif %}
</ul>
{% endblock %}
 <!-- ----- END INDEX NAV ----- -->
{% block content %}
<div class="header_image_zblog">
  <h1>zBlog</h1>
  <h5>A Better Beer Blog</h5>
</div>

<div class="container centerstage">
  <h1>New Comment</h1>
  <form class="post-form" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="save btn btn-default" type="submit">Post Comment</button>
  </form>
</div>

<script>
  var editor = new MediumEditor('.editable');
</script>
{% endblock %}

ZachStallPortfolio/templates/zBLOG/post_confirm_delete.html
{% extends "base.html" %}
{% load staticfiles %}


 <!-- ----- INDEX NAV ----- -->
{% block nav %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'zBLOG:zblog_about' %}">zBlog About</a>
  </li>
</ul>
<ul class="navbar-nav ml-auto">
{% if user.is_authenticated %}
  <li class="nav-item ml-auto">
    <a class="nav-link" href="{% url 'zBLOG:post_new' %}">New Post</a>
  </li>
  <li class="nav-item ml-auto">
    <a class="nav-link navbar-right" href="{% url 'zBLOG:post_draft_list' %}">Drafts</a>
  </li>
  <li class="nav-item ml-auto">
    <a class="nav-link navbar-right" href="{% url 'logout' %}">Log Out</a>
  </li>
  <li class="nav-item ml-auto">
    <a class="nav-link navbar-right">Welcome: {{user.username}}</a>
  </li>
{% else %}
  <li class="nav-item ml-auto">
    <a class="nav-link ml-auto" href="{% url 'login' %}">Login</a>
  </li>
{% endif %}
</ul>
{% endblock %}
 <!-- ----- END INDEX NAV ----- -->
{% block content %}
<div class="header_image_zblog">
  <h1>zBlog</h1>
  <h5>A Better Beer Blog</h5>
</div>
<form method="POST">
  {% csrf_token %}
  <p>Are you sure you want to delete {{ object }}</p>
  <input class="btn btn-danger" type="submit" value="Confirm">
</form>
{% endblock %}

ZachStallPortfolio/templates/zBLOG/post_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load embed_video_tags %}

 <!-- ----- INDEX NAV ----- -->
{% block nav %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'zBLOG:zblog_about' %}">zBlog About</a>
  </li>
</ul>
<ul class="navbar-nav ml-auto">
{% if user.is_authenticated %}
  <li class="nav-item ml-auto">
    <a class="nav-link" href="{% url 'zBLOG:post_new' %}">New Post</a>
  </li>
  <li class="nav-item ml-auto">
    <a class="nav-link navbar-right" href="{% url 'zBLOG:post_draft_list' %}">Drafts</a>
  </li>
  <li class="nav-item ml-auto">
    <a class="nav-link navbar-right" href="{% url 'logout' %}">Log Out</a>
  </li>
  <li class="nav-item ml-auto">
    <a class="nav-link navbar-right">Welcome: {{user.username}}</a>
  </li>
{% else %}
  <li class="nav-item ml-auto">
    <a class="nav-link ml-auto" href="{% url 'login' %}">Login</a>
  </li>
{% endif %}
</ul>
{% endblock %}
 <!-- ----- END INDEX NAV ----- -->
{% block content %}
<div class="post_header_image_zblog">
  <h1 class="post_tittle">{{ post.title }}</h1>
  <h5 class="post_title">{{ post.sub_title }}</h5>
</div>
<div class="container centerstage">
  <!-- {% if post.published_date %}
    <div class="date postdate">
      {{ post.published_date }}
    </div>
  {% else %}
  <br>
  <a class="btn btn-primary" href="{% url 'zBLOG:post_publish' pk=post.pk %}">Publish</a>
  <br>
  {% endif %} -->
  <div class="row">
    <div class="col-lg-4">
      <img class="post-image" src="{{ post.blog_image.url }}" alt="">
    </div>
    <div class="col-lg-8">
      {% if post.published_date %}
        <div class="date postdate">
          <p>Posted on: {{ post.published_date }}</p>
        </div>
      {% else %}
      <br>
      <a class="btn btn-primary" href="{% url 'zBLOG:post_publish' pk=post.pk %}">Publish</a>
      <br>
      {% endif %}
      <p class="postcontent">{{ post.text|safe|linebreaksbr }}</p>
      {% if user.is_authenticated %}
        <a class="btn btn-primary" href="{% url 'zBLOG:post_edit' pk=post.pk %}">
          Edit
        </a>
        <a class="btn btn-danger" href="{% url 'zBLOG:post_remove' pk=post.pk %}">
          Delete
        </a>
        <br><br>
      {% endif %}
      <div class="embed_video">
          {% video post.post_video 'small' %}
      </div>
    </div>
  </div>



  <div class="col-md-3">
    <!-- {# <img class="post-image" src="{{ post.blog_image.url }}" alt=""> #} -->
    <br>
    <br>
    <a class="btn btn-primary" href="{% url 'zBLOG:add_comment_to_post' pk=post.pk %}">
      Add a Comment
    </a>

  </div>
  <div class="col-md-8">


    <hr>
    <div class="container">

      <p>All comments will be approved before they are posted.</p>

      {% for comment in post.comments.all %}
        <br>

        {% if user.is_authenticated and comment.approved_comment %}
          <hr>
          <a class="btn btn-danger btn-xs btn-comment" href="{% url 'zBLOG:comment_remove' pk=comment.pk %}">
            Delete
          </a>
        {% endif %}


        {% if user.is_authenticated or comment.approved_comment %}
          {{ comment.created_date }}
            {% if not comment.approved_comment %}
            <a class="btn btn-default" href="{% url 'zBLOG:comment_remove' pk=comment.pk %}">
              Delete
            </a>
            <a class="btn btn-primary" href="{% url 'zBLOG:comment_approve' pk=comment.pk %}">
              Okay
            </a>
            {% endif %}
            <p>{{comment.text|safe|linebreaks}}</p>
            <p>Posted By: {{comment.author}}</p>
        {% endif %}
        {% empty %}
        <p>No Comments.</p>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

ZachStallPortfolio/templates/zBLOG/post_draft_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% load embed_video_tags %}

 <!-- ----- INDEX NAV ----- -->
{% block nav %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'zBLOG:zblog_about' %}">zBlog About</a>
  </li>
</ul>
<ul class="navbar-nav ml-auto">
{% if user.is_authenticated %}
  <li class="nav-item ml-auto">
    <a class="nav-link" href="{% url 'zBLOG:post_new' %}">New Post</a>
  </li>
  <li class="nav-item ml-auto">
    <a class="nav-link navbar-right" href="{% url 'zBLOG:post_draft_list' %}">Drafts</a>
  </li>
  <li class="nav-item ml-auto">
    <a class="nav-link navbar-right" href="{% url 'logout' %}">Log Out</a>
  </li>
  <li class="nav-item ml-auto">
    <a class="nav-link navbar-right">Welcome: {{user.username}}</a>
  </li>
{% else %}
  <li class="nav-item ml-auto">
    <a class="nav-link ml-auto" href="{% url 'login' %}">Login</a>
  </li>
{% endif %}
</ul>
{% endblock %}
 <!-- ----- END INDEX NAV ----- -->

{% block content %}
  <div class="header_image_zblog">
    <h1>zBlog</h1>
    <h5>A Better Beer Blog</h5>
  </div>
  {% for post in posts %}
      <div class="post">
        <p class='date'>created: {{[post.created_date|date:'d-m-Y']}}</p>
        <h1><a href="{% url 'BetterBeerBlog:post_detail' pk=post.pk %}">{{post.title}}</a></h1>
        <p>{{post.text|truncatechars:200}}</p>
      </div>
    {% endfor %}
  {% endblock %}

ZachStallPortfolio/templates/zBLOG/post_form.html
{% extends "base.html" %}
{% load staticfiles %}
{% load embed_video_tags %}

 <!-- ----- INDEX NAV ----- -->
{% block nav %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'zBLOG:zblog_about' %}">zBlog About</a>
  </li>
</ul>
<ul class="navbar-nav ml-auto">
{% if user.is_authenticated %}
  <li class="nav-item ml-auto">
    <a class="nav-link" href="{% url 'zBLOG:post_new' %}">New Post</a>
  </li>
  <li class="nav-item ml-auto">
    <a class="nav-link navbar-right" href="{% url 'zBLOG:post_draft_list' %}">Drafts</a>
  </li>
  <li class="nav-item ml-auto">
    <a class="nav-link navbar-right" href="{% url 'logout' %}">Log Out</a>
  </li>
  <li class="nav-item ml-auto">
    <a class="nav-link navbar-right">Welcome: {{user.username}}</a>
  </li>
{% else %}
  <li class="nav-item ml-auto">
    <a class="nav-link ml-auto" href="{% url 'login' %}">Login</a>
  </li>
{% endif %}
</ul>
{% endblock %}
 <!-- ----- END INDEX NAV ----- -->

{% block content %}
  <div class="header_image_zblog">
    <h1>zBlog</h1>
    <h5>A Better Beer Blog</h5>
  </div>

  <div class="container centerstage">
    <h1>Create/Edit your post here</h1>
    <form class="post-form" enctype="multipart/form-data" method="POST">
      {% csrf_token %}
      {{form.as_p}}
      <button class="save btn btn-default" type="submit">Save</button>
    </form>
  </div>

  <script>var editor = new MediumEditor('.editable');</script>
{% endblock %}

ZachStallPortfolio/templates/zBLOG/post_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% load embed_video_tags %}

 <!-- ----- INDEX NAV ----- -->
{% block nav %}
<!-- So much nav, so little time... -->
  <li class="nav-item">
    <a class="nav-link" href="{% url 'zBLOG:zblog_about' %}">zBlog About</a>
  </li>
</ul>
<ul class="navbar-nav ml-auto">
{% if user.is_authenticated %}
  <li class="nav-item ml-auto">
    <a class="nav-link" href="{% url 'zBLOG:post_new' %}">New Post</a>
  </li>
  <li class="nav-item ml-auto">
    <a class="nav-link navbar-right" href="{% url 'zBLOG:post_draft_list' %}">Drafts</a>
  </li>
  <li class="nav-item ml-auto">
    <a class="nav-link navbar-right" href="{% url 'logout' %}">Log Out</a>
  </li>
  <li class="nav-item ml-auto">
    <a class="nav-link navbar-right">Welcome: {{user.username}}</a>
  </li>
{% else %}
  <li class="nav-item ml-auto">
    <a class="nav-link ml-auto" href="{% url 'login' %}">Login</a>
  </li>
{% endif %}
</ul>
{% endblock %}
 <!-- ----- END INDEX NAV ----- -->

{% block content %}
<div class="header_image_zblog">
  <h1>zBlog</h1>
  <h5>A Better Beer Blog</h5>
</div>
<div class="container">
  <div class="row">
    <div class="col-7">
      <div class="row">
        <div class="post-container">
          {% for post in post_list %}
            <div class="post">
              <h1><a href="{% url 'zBLOG:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
              <h5><a href="{% url 'zBLOG:post_detail' pk=post.pk %}">{{ post.sub_title }}</a></h5>
              <div class="date">
                <p><strong>Published on:</strong> {{post.published_date}}</p>
              </div>
              <a href="{% url 'zBLOG:post_detail' pk=post.pk %}">Comments: {{ post.approve_comments.count }}</a>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
    <div class="col-4">
      <div class="row">
        <img class="home-images" src="{% static 'zBLOG/solera-beer.jpg' %}" alt="">
      </div>
      <div class="row">
        <img class="home-images" src="{% static 'zBLOG/solera-beer.jpg' %}" alt="">
      </div>
      <div class="row">
        <img class="home-images" src="{% static 'zBLOG/solera-beer.jpg' %}" alt="">
      </div>
      <div class="row">
        <img class="home-images" src="{% static 'zBLOG/solera-beer-kitchen.jpg' %}" alt="">
      </div>
      <div class="row">
        <img class="home-images" src="{% static 'zBLOG/solera-beer-kitchen.jpg' %}" alt="">
      </div>
      <div class="row">
        <img class="home-images" src="{% static 'zBLOG/solera-beer-kitchen.jpg' %}" alt="">
      </div>
    </div>
  </div>
</div>
{% endblock %}